import type { MatchSummary } from "./domain";

export const sampleMatches: MatchSummary[] = [
  {
    id: "mx-fr",
    status: "Live",
    minute: "62'",
    group: "Group A",
    time: "Now",
    venue: "Estadio Azteca",
    city: "Mexico City",
    score: "1 - 1",
    home: {
      name: "Mexico",
      code: "MEX",
      color: "#11a36a",
      record: "2W 1D 2L",
      form: ["W", "D", "L", "W", "L"],
      attack: 74,
      control: 71,
      defense: 69,
      setPieces: 78,
    },
    away: {
      name: "France",
      code: "FRA",
      color: "#3157ff",
      record: "4W 1D 0L",
      form: ["W", "W", "D", "W", "W"],
      attack: 88,
      control: 84,
      defense: 81,
      setPieces: 73,
    },
    forecast: {
      home: 29,
      draw: 27,
      away: 44,
      confidence: 68,
      chaos: 61,
      projected: "1-2 / 2-2",
      tone: {
        en: "France carry the brighter signal, but Mexico have the altitude spark and a loud-stadium weather system.",
        es: "Francia trae la señal más fuerte, pero México tiene chispa de altura y un estadio que empuja como tormenta.",
        fr: "La France garde le signal le plus net, mais le Mexique a l’altitude et un stade qui peut tourner le vent.",
      },
      reasons: {
        en: [
          "France own the cleaner attack profile.",
          "Mexico improve at altitude and on set pieces.",
          "The live score keeps draw weather very alive.",
        ],
        es: [
          "Francia tiene el perfil ofensivo más claro.",
          "México mejora con altura y balón parado.",
          "El marcador en vivo mantiene muy vivo el empate.",
        ],
        fr: [
          "La France possède le profil offensif le plus net.",
          "Le Mexique gagne en altitude et sur phases arrêtées.",
          "Le score en direct garde le nul très présent.",
        ],
      },
    },
    weather: {
      temp: "23°C",
      wind: "11 km/h",
      mood: {
        en: "Thin air, fast counters, late legs.",
        es: "Aire ligero, contragolpes rápidos, piernas pesadas al final.",
        fr: "Air fin, contres rapides, jambes lourdes en fin de match.",
      },
    },
    referee: { name: "A. Marciniak", cardRisk: "Medium-high" },
    players: [
      {
        name: "Santiago Giménez",
        team: "Mexico",
        role: "Forward",
        club: "Feyenoord",
        league: "Eredivisie",
        spark: 76,
        note: "Box gravity",
      },
      {
        name: "Kylian Mbappé",
        team: "France",
        role: "Forward",
        club: "Real Madrid",
        league: "La Liga",
        spark: 94,
        note: "Open-field storm",
      },
      {
        name: "Edson Álvarez",
        team: "Mexico",
        role: "Midfielder",
        club: "West Ham",
        league: "Premier League",
        spark: 80,
        note: "Duel anchor",
      },
    ],
  },
  {
    id: "br-jp",
    status: "Upcoming",
    group: "Group C",
    time: "5:00 PM",
    venue: "MetLife Stadium",
    city: "New Jersey",
    home: {
      name: "Brazil",
      code: "BRA",
      color: "#f5c542",
      record: "3W 1D 1L",
      form: ["W", "W", "L", "D", "W"],
      attack: 91,
      control: 86,
      defense: 77,
      setPieces: 72,
    },
    away: {
      name: "Japan",
      code: "JPN",
      color: "#e83d52",
      record: "4W 0D 1L",
      form: ["W", "W", "W", "L", "W"],
      attack: 79,
      control: 82,
      defense: 80,
      setPieces: 69,
    },
    forecast: {
      home: 53,
      draw: 23,
      away: 24,
      confidence: 72,
      chaos: 47,
      projected: "2-1",
      tone: {
        en: "Brazil glow in attack, but Japan keep enough transition static to make the Seer sit forward.",
        es: "Brasil brilla en ataque, pero Japón tiene suficiente electricidad en transición para incomodar al Vidente.",
        fr: "Le Brésil brille devant, mais le Japon garde assez d’électricité en transition pour réveiller le voyant.",
      },
      reasons: {
        en: [
          "Brazil lead in shot creation and individual spark.",
          "Japan narrow the midfield gap with tempo.",
          "Weather looks clean enough for a technical match.",
        ],
        es: [
          "Brasil lidera en creación y talento individual.",
          "Japón reduce la distancia con ritmo en medio campo.",
          "El clima favorece un partido técnico.",
        ],
        fr: [
          "Le Brésil domine la création et l’étincelle individuelle.",
          "Le Japon réduit l’écart avec son rythme au milieu.",
          "La météo favorise un match technique.",
        ],
      },
    },
    weather: {
      temp: "26°C",
      wind: "8 km/h",
      mood: {
        en: "Warm, clean, friendly to first touch.",
        es: "Cálido, limpio, amable para el primer toque.",
        fr: "Doux, clair, favorable au premier contrôle.",
      },
    },
    referee: { name: "M. Oliver", cardRisk: "Medium" },
    players: [
      {
        name: "Vinícius Júnior",
        team: "Brazil",
        role: "Winger",
        club: "Real Madrid",
        league: "La Liga",
        spark: 92,
        note: "Left-lane lightning",
      },
      {
        name: "Takefusa Kubo",
        team: "Japan",
        role: "Creator",
        club: "Real Sociedad",
        league: "La Liga",
        spark: 84,
        note: "Pocket mischief",
      },
    ],
  },
  {
    id: "ca-ma",
    status: "Upcoming",
    group: "Group F",
    time: "8:00 PM",
    venue: "BMO Field",
    city: "Toronto",
    home: {
      name: "Canada",
      code: "CAN",
      color: "#e1251b",
      record: "2W 2D 1L",
      form: ["D", "W", "W", "L", "D"],
      attack: 77,
      control: 73,
      defense: 72,
      setPieces: 75,
    },
    away: {
      name: "Morocco",
      code: "MAR",
      color: "#c1272d",
      record: "3W 1D 1L",
      form: ["W", "D", "W", "W", "L"],
      attack: 78,
      control: 79,
      defense: 86,
      setPieces: 80,
    },
    forecast: {
      home: 31,
      draw: 30,
      away: 39,
      confidence: 59,
      chaos: 66,
      projected: "1-1 / 1-2",
      tone: {
        en: "Morocco bring the steadier defensive moon, but Canada have enough pace to make this forecast wobble.",
        es: "Marruecos trae una luna defensiva más estable, pero Canadá tiene velocidad suficiente para mover el pronóstico.",
        fr: "Le Maroc apporte une lune défensive plus stable, mais le Canada a assez de vitesse pour faire trembler la prévision.",
      },
      reasons: {
        en: [
          "Morocco rate higher in defensive structure.",
          "Canada’s wide pace lifts upset risk.",
          "The draw lane is unusually open.",
        ],
        es: [
          "Marruecos puntúa mejor en estructura defensiva.",
          "La velocidad por fuera de Canadá sube el riesgo de sorpresa.",
          "El camino del empate está muy abierto.",
        ],
        fr: [
          "Le Maroc est plus solide dans sa structure défensive.",
          "La vitesse canadienne sur les côtés augmente le risque de surprise.",
          "La voie du nul reste très ouverte.",
        ],
      },
    },
    weather: {
      temp: "18°C",
      wind: "17 km/h",
      mood: {
        en: "Cool breeze, cross-heavy, set-piece friendly.",
        es: "Brisa fresca, muchos centros, buen clima para balón parado.",
        fr: "Brise fraîche, beaucoup de centres, phases arrêtées favorisées.",
      },
    },
    referee: { name: "S. Frappart", cardRisk: "Medium-low" },
    players: [
      {
        name: "Alphonso Davies",
        team: "Canada",
        role: "Wingback",
        club: "Bayern Munich",
        league: "Bundesliga",
        spark: 90,
        note: "Left-side ignition",
      },
      {
        name: "Achraf Hakimi",
        team: "Morocco",
        role: "Fullback",
        club: "PSG",
        league: "Ligue 1",
        spark: 88,
        note: "Two-way engine",
      },
    ],
  },
];

export function getSampleMatch(matchId: string) {
  return sampleMatches.find((match) => match.id === matchId);
}

